data_path: ./   # 数据存放路径

# 匹配
# TODO: implement your custom registration method and add it here
# 选择点云匹配方法，目前支持：ICP, ICP_SVD, NDT, SICP, OMP_NDT, NDT_CPU, FAST_GICP, FAST_VGICP
registration_method: NDT_CPU   

# 局部地图
key_frame_distance: 2.0 # 关键帧距离
local_frame_num: 20
local_map_filter: voxel_filter # 选择滑窗地图点云滤波方法，目前支持：voxel_filter

# rviz显示
display_filter: voxel_filter # rviz 实时显示点云时滤波方法，目前支持：voxel_filter

# 当前帧
frame_filter: voxel_filter # 选择当前帧点云滤波方法，目前支持：voxel_filter

## 滤波相关参数
voxel_filter:
    local_map:
        leaf_size: [0.6, 0.6, 0.6]
    frame:
        leaf_size: [1.3, 1.3, 1.3]
    display:
        leaf_size: [0.5, 0.5, 0.5]

# 各配置选项对应参数
## 匹配相关参数
ICP:
    max_corr_dist : 1.2
    trans_eps : 0.01
    euc_fitness_eps : 0.36
    max_iter : 30
ICP_SVD:
    max_corr_dist : 1.2
    trans_eps : 0.01
    euc_fitness_eps : 0.36
    max_iter : 10
NDT:
    res : 1.0
    step_size : 0.1
    trans_eps : 0.01
    max_iter : 30
SICP:
    p : 1
    mu : 10.0
    alpha : 1.2
    max_mu : 1e5
    max_icp : 100
    max_outer : 100
    max_inner : 1
    stop : 1e-5
OMP_NDT:
    resolution : 1.0
    step_size : 0.1
    epsilon : 0.01
    num_threads : 10 
    search_method : 2 # 1:KDTREE 2:DIRECT7 3:DIRECT1
    max_iter : 30
NDT_CPU:
    trans_eps : 0.01
    step_size : 0.10
    ndt_resolution : 1.0
    max_iter : 30
FAST_GICP:
    num_threads : 4
    max_correspondence_dis : 1.0
FAST_VGICP:
    num_threads : 4
    max_correspondence_dis : 1.0
    